import "server-only";
import { randomBytes } from "node:crypto";
import { and, desc, eq, ilike, inArray, lt, or, sql } from "drizzle-orm";
import { scopedDb } from "@/shared/db/rls";
import {
  meetingRecords,
  meetingRecordStatusEnum,
  type MeetingRecordRow,
  type NewMeetingRecordRow,
} from "@/shared/db/schema";

/** Persisted meeting status values (from the DB enum) — for filter validation. */
export type MeetingRecordStatus = (typeof meetingRecordStatusEnum.enumValues)[number];
const MEETING_STATUSES = new Set<string>(meetingRecordStatusEnum.enumValues);

/** True if `s` is a valid meeting_record status (for query-param filtering). */
export function isMeetingStatus(s: string): s is MeetingRecordStatus {
  return MEETING_STATUSES.has(s);
}

/**
 * Repository for persisted meeting minutes (meeting_records) — capability boundary.
 *
 * The minutes generated by the LLM are the app's source of truth: Recall
 * cleans up the transcript/artifacts days after the meeting. Persisting here
 * avoids re-fetching from Recall and re-paying the LLM on every read, and
 * enables the reconciliation cron to sweep minutes stuck in pending/processing.
 */

/** One row of the meetings list (index). Only the columns the list renders. */
export type MeetingListItem = Pick<
  MeetingRecordRow,
  "botId" | "status" | "meetingUrl" | "summary" | "createdAt" | "updatedAt"
> & { participantCount: number; durationSeconds: number | null };

/**
 * Approximate meeting length for the LIST, without loading the heavy word-level
 * `transcriptStruct` jsonb per row. Takes the largest timestamp across the small
 * summary jsonbs (soundbite ends, moment/section points). It's a floor (the last
 * flagged moment), good enough for the list; the detail view computes the exact
 * length from the full transcript. Null when no timed markers exist.
 */
function deriveListDuration(row: {
  moments: MeetingRecordRow["moments"];
  sections: MeetingRecordRow["sections"];
  soundbites: MeetingRecordRow["soundbites"];
}): number | null {
  let max = 0;
  for (const s of row.soundbites ?? []) {
    if (s.endSeconds > max) max = s.endSeconds;
  }
  for (const m of row.moments ?? []) {
    if (m.atSeconds != null && m.atSeconds > max) max = m.atSeconds;
  }
  for (const s of row.sections ?? []) {
    if (s.startSeconds != null && s.startSeconds > max) max = s.startSeconds;
  }
  return max > 0 ? Math.round(max) : null;
}

/**
 * Lists the user's meeting minutes for the index, most recent first.
 *
 * RLS-scoped: runs under withUserScope, so it only returns the caller's rows.
 * `talkShares` doubles as the participant count for the list avatars without
 * having to re-fetch from Recall.
 */
export async function listMeetingRecordsForUser(
  limit = 100,
): Promise<MeetingListItem[]> {
  const rows = await scopedDb()
    .select({
      botId: meetingRecords.botId,
      status: meetingRecords.status,
      meetingUrl: meetingRecords.meetingUrl,
      summary: meetingRecords.summary,
      talkShares: meetingRecords.talkShares,
      moments: meetingRecords.moments,
      sections: meetingRecords.sections,
      soundbites: meetingRecords.soundbites,
      createdAt: meetingRecords.createdAt,
      updatedAt: meetingRecords.updatedAt,
    })
    .from(meetingRecords)
    .orderBy(desc(meetingRecords.createdAt))
    .limit(limit);

  return rows.map(({ talkShares, moments, sections, soundbites, ...r }) => ({
    ...r,
    participantCount: talkShares?.length ?? 0,
    durationSeconds: deriveListDuration({ moments, sections, soundbites }),
  }));
}

/** A page of meetings + the cursor to fetch the next one (null when exhausted). */
export interface MeetingPage {
  items: MeetingListItem[];
  /** Opaque cursor (ISO createdAt of the last item) for the next page. */
  nextCursor: string | null;
}

export interface MeetingPageQuery {
  /** Keyword: matched (case-insensitive) against summary/overview/transcript. */
  query?: string;
  /** Filter to a single record status (done/processing/pending/failed). */
  status?: MeetingRecordStatus;
  /** Keyset cursor: return rows strictly OLDER than this ISO createdAt. */
  cursor?: string;
  /** Page size (clamped 1..100 by the caller). Default 30. */
  limit?: number;
}

/**
 * Paginated, server-side-searched meetings index — the "library" query.
 *
 * Replaces client-side filtering over a 100-row cap: search runs in the DB
 * (ILIKE over summary/overview/transcript, same predicate as the agent's
 * search), status filters in SQL, and keyset pagination on createdAt keeps it
 * stable as new meetings arrive (no OFFSET drift). RLS-scoped: MUST run under
 * withUserScope — scopedDb() filters to the caller.
 */
export async function listMeetingRecordsPage(
  input: MeetingPageQuery = {},
): Promise<MeetingPage> {
  const limit = Math.min(100, Math.max(1, input.limit ?? 30));

  const conds = [];
  const q = input.query?.trim();
  if (q) {
    const pattern = `%${q.replace(/[%_]/g, (c) => `\\${c}`)}%`;
    conds.push(
      or(
        ilike(meetingRecords.summary, pattern),
        ilike(meetingRecords.overview, pattern),
        ilike(meetingRecords.transcript, pattern),
      ),
    );
  }
  if (input.status) conds.push(eq(meetingRecords.status, input.status));
  // Keyset: next page = rows strictly older than the last createdAt seen.
  if (input.cursor) conds.push(lt(meetingRecords.createdAt, new Date(input.cursor)));

  // Fetch limit+1 to know whether a further page exists without a count query.
  const rows = await scopedDb()
    .select({
      botId: meetingRecords.botId,
      status: meetingRecords.status,
      meetingUrl: meetingRecords.meetingUrl,
      summary: meetingRecords.summary,
      talkShares: meetingRecords.talkShares,
      moments: meetingRecords.moments,
      sections: meetingRecords.sections,
      soundbites: meetingRecords.soundbites,
      createdAt: meetingRecords.createdAt,
      updatedAt: meetingRecords.updatedAt,
    })
    .from(meetingRecords)
    .where(conds.length ? and(...conds) : undefined)
    .orderBy(desc(meetingRecords.createdAt))
    .limit(limit + 1);

  const hasMore = rows.length > limit;
  const page = hasMore ? rows.slice(0, limit) : rows;
  const items = page.map(
    ({ talkShares, moments, sections, soundbites, ...r }) => ({
      ...r,
      participantCount: talkShares?.length ?? 0,
      durationSeconds: deriveListDuration({ moments, sections, soundbites }),
    }),
  );
  const nextCursor = hasMore
    ? page[page.length - 1].createdAt.toISOString()
    : null;

  return { items, nextCursor };
}

/** One search hit: enough context for the agent to answer without a re-fetch. */
export type MeetingSearchHit = Pick<
  MeetingRecordRow,
  "botId" | "summary" | "overview" | "topics" | "createdAt"
> & { snippet: string | null };

/**
 * Full-text-ish search across the caller's persisted minutes — powers the
 * agent's cross-meeting Q&A ("what did we decide about pricing?"). Matches
 * `query` against summary/overview/transcript (case-insensitive ILIKE) and
 * returns the top hits with a short transcript snippet around the match.
 *
 * RLS-scoped: MUST run under withUserScope — scopedDb() filters to the caller.
 * ILIKE (no tsvector/GIN yet) keeps this migration-free; revisit if slow at scale.
 */
export async function searchMeetingRecords(
  query: string,
  limit = 5,
): Promise<MeetingSearchHit[]> {
  const q = query.trim();
  if (!q) return [];
  const pattern = `%${q.replace(/[%_]/g, (c) => `\\${c}`)}%`;

  const rows = await scopedDb()
    .select({
      botId: meetingRecords.botId,
      summary: meetingRecords.summary,
      overview: meetingRecords.overview,
      topics: meetingRecords.topics,
      transcript: meetingRecords.transcript,
      createdAt: meetingRecords.createdAt,
    })
    .from(meetingRecords)
    .where(
      and(
        eq(meetingRecords.status, "done"),
        or(
          ilike(meetingRecords.summary, pattern),
          ilike(meetingRecords.overview, pattern),
          ilike(meetingRecords.transcript, pattern),
        ),
      ),
    )
    .orderBy(desc(meetingRecords.createdAt))
    .limit(limit);

  return rows.map(({ transcript, ...r }) => ({
    ...r,
    snippet: transcriptSnippet(transcript, q),
  }));
}

/** Extracts a ~240-char window of the transcript around the first match. */
function transcriptSnippet(
  transcript: string | null,
  query: string,
): string | null {
  if (!transcript) return null;
  const idx = transcript.toLowerCase().indexOf(query.toLowerCase());
  if (idx < 0) return null;
  const start = Math.max(0, idx - 80);
  const end = Math.min(transcript.length, idx + query.length + 160);
  const prefix = start > 0 ? "…" : "";
  const suffix = end < transcript.length ? "…" : "";
  return `${prefix}${transcript.slice(start, end).trim()}${suffix}`;
}

/** Returns the persisted minutes of a bot, or null. */
export async function findMeetingRecord(
  botId: string,
): Promise<MeetingRecordRow | null> {
  const rows = await scopedDb()
    .select()
    .from(meetingRecords)
    .where(eq(meetingRecords.botId, botId))
    .limit(1);
  return rows[0] ?? null;
}

/* ── public sharing ───────────────────────────────────────────────────── */

/** Current share state of a meeting (for the owner's Share control). */
export interface MeetingShareState {
  shareToken: string | null;
  shareCreatedAt: Date | null;
}

/**
 * Enables a public share link for the meeting (idempotent-ish): if it already
 * has a token, returns it unchanged; otherwise mints a new unguessable one.
 *
 * RLS-scoped: MUST run under withUserScope — only the owner can share their
 * meeting (scopedDb() filters to the caller, so a non-owner update hits 0 rows).
 * Returns null if the meeting doesn't exist / isn't the caller's.
 */
export async function enableMeetingShare(
  botId: string,
): Promise<MeetingShareState | null> {
  const existing = await findMeetingRecord(botId);
  if (!existing) return null;
  if (existing.shareToken) {
    return {
      shareToken: existing.shareToken,
      shareCreatedAt: existing.shareCreatedAt,
    };
  }
  // 32 hex chars = 128 bits of entropy — unguessable, URL-safe.
  const token = randomBytes(16).toString("hex");
  const now = new Date();
  const rows = await scopedDb()
    .update(meetingRecords)
    .set({ shareToken: token, shareCreatedAt: now, updatedAt: now })
    .where(eq(meetingRecords.botId, botId))
    .returning({
      shareToken: meetingRecords.shareToken,
      shareCreatedAt: meetingRecords.shareCreatedAt,
    });
  return rows[0] ?? null;
}

/**
 * Revokes the public share link (clears the token). Idempotent.
 * RLS-scoped: MUST run under withUserScope.
 */
export async function disableMeetingShare(botId: string): Promise<void> {
  await scopedDb()
    .update(meetingRecords)
    .set({ shareToken: null, shareCreatedAt: null, updatedAt: new Date() })
    .where(eq(meetingRecords.botId, botId));
}

/**
 * Looks up a meeting by its public share token — the ONLY read that returns a
 * meeting to an UNAUTHENTICATED caller. Filters on the token AND status="done"
 * so only ready minutes are ever public.
 *
 * MUST run under withSystemScope: the public page has no user, so RLS would
 * fail-closed. The unguessable token IS the authorization; the query narrows to
 * that single row. Returns null when the token is unknown / revoked / not done.
 */
export async function findMeetingByShareToken(
  token: string,
): Promise<MeetingRecordRow | null> {
  if (!token) return null;
  const rows = await scopedDb()
    .select()
    .from(meetingRecords)
    .where(
      and(
        eq(meetingRecords.shareToken, token),
        eq(meetingRecords.status, "done"),
      ),
    )
    .limit(1);
  return rows[0] ?? null;
}

/**
 * Enqueues minutes (status=pending). Idempotent: if it already exists, doesn't
 * overwrite (enrichment/reconcile handle the state transition). Used by the webhook.
 */
export async function enqueueMeetingRecord(input: {
  botId: string;
  userId?: string | null;
  meetingUrl?: string | null;
}): Promise<void> {
  await scopedDb()
    .insert(meetingRecords)
    .values({
      botId: input.botId,
      userId: input.userId ?? null,
      meetingUrl: input.meetingUrl ?? null,
      status: "pending",
    })
    .onConflictDoNothing({ target: meetingRecords.botId });
}

/**
 * Marks the minutes as "processing" and increments attempts, but ONLY if not
 * already "done" — avoids reprocessing minutes that are already ready. Returns
 * the claimed row (for the worker to proceed) or null if it was already done/nonexistent.
 */
export async function claimMeetingRecord(
  botId: string,
): Promise<MeetingRecordRow | null> {
  const rows = await scopedDb()
    .update(meetingRecords)
    .set({
      status: "processing",
      attempts: sql`${meetingRecords.attempts} + 1`,
      updatedAt: new Date(),
    })
    .where(
      and(
        eq(meetingRecords.botId, botId),
        inArray(meetingRecords.status, ["pending", "processing", "failed"]),
      ),
    )
    .returning();
  return rows[0] ?? null;
}

/** Persists the generated minutes and marks done. */
export async function completeMeetingRecord(
  botId: string,
  data: Omit<
    NewMeetingRecordRow,
    "botId" | "status" | "attempts" | "createdAt" | "updatedAt"
  >,
): Promise<void> {
  await scopedDb()
    .update(meetingRecords)
    .set({ ...data, status: "done", error: null, updatedAt: new Date() })
    .where(eq(meetingRecords.botId, botId));
}

/** Marks the minutes as permanently failed (after exhausting retries). */
export async function failMeetingRecord(
  botId: string,
  error: string,
): Promise<void> {
  await scopedDb()
    .update(meetingRecords)
    .set({ status: "failed", error, updatedAt: new Date() })
    .where(eq(meetingRecords.botId, botId));
}

/**
 * Moves the minutes back to "pending" (transient retry: transcript still
 * processing, or recoverable error). The reconciliation cron picks it up on
 * the next tick.
 */
export async function requeueMeetingRecord(
  botId: string,
  note: string,
): Promise<void> {
  await scopedDb()
    .update(meetingRecords)
    .set({ status: "pending", error: note, updatedAt: new Date() })
    .where(eq(meetingRecords.botId, botId));
}

/**
 * Returns botIds of minutes stuck for the reconciliation cron: pending for
 * more than `staleMs`, or failed (for a new attempt). Doesn't touch
 * done/recently processing.
 */
export async function listStuckMeetingRecords(
  staleMs: number,
): Promise<string[]> {
  const threshold = new Date(Date.now() - staleMs);
  const rows = await scopedDb()
    .select({ botId: meetingRecords.botId })
    .from(meetingRecords)
    .where(
      or(
        and(
          eq(meetingRecords.status, "pending"),
          lt(meetingRecords.updatedAt, threshold),
        ),
        and(
          eq(meetingRecords.status, "processing"),
          lt(meetingRecords.updatedAt, threshold),
        ),
      ),
    );
  return rows.map((r) => r.botId);
}
