import "server-only";
import { and, eq, inArray, lt, or, sql } from "drizzle-orm";
import { scopedDb } from "@/shared/db/rls";
import {
  meetingRecords,
  type MeetingRecordRow,
  type NewMeetingRecordRow,
} from "@/shared/db/schema";

/**
 * Repository for persisted meeting minutes (meeting_records) — capability boundary.
 *
 * The minutes generated by the LLM are the app's source of truth: Recall
 * cleans up the transcript/artifacts days after the meeting. Persisting here
 * avoids re-fetching from Recall and re-paying the LLM on every read, and
 * enables the reconciliation cron to sweep minutes stuck in pending/processing.
 */

/** Returns the persisted minutes of a bot, or null. */
export async function findMeetingRecord(
  botId: string,
): Promise<MeetingRecordRow | null> {
  const rows = await scopedDb()
    .select()
    .from(meetingRecords)
    .where(eq(meetingRecords.botId, botId))
    .limit(1);
  return rows[0] ?? null;
}

/**
 * Enqueues minutes (status=pending). Idempotent: if it already exists, doesn't
 * overwrite (enrichment/reconcile handle the state transition). Used by the webhook.
 */
export async function enqueueMeetingRecord(input: {
  botId: string;
  userId?: string | null;
  meetingUrl?: string | null;
}): Promise<void> {
  await scopedDb()
    .insert(meetingRecords)
    .values({
      botId: input.botId,
      userId: input.userId ?? null,
      meetingUrl: input.meetingUrl ?? null,
      status: "pending",
    })
    .onConflictDoNothing({ target: meetingRecords.botId });
}

/**
 * Marks the minutes as "processing" and increments attempts, but ONLY if not
 * already "done" — avoids reprocessing minutes that are already ready. Returns
 * the claimed row (for the worker to proceed) or null if it was already done/nonexistent.
 */
export async function claimMeetingRecord(
  botId: string,
): Promise<MeetingRecordRow | null> {
  const rows = await scopedDb()
    .update(meetingRecords)
    .set({
      status: "processing",
      attempts: sql`${meetingRecords.attempts} + 1`,
      updatedAt: new Date(),
    })
    .where(
      and(
        eq(meetingRecords.botId, botId),
        inArray(meetingRecords.status, ["pending", "processing", "failed"]),
      ),
    )
    .returning();
  return rows[0] ?? null;
}

/** Persists the generated minutes and marks done. */
export async function completeMeetingRecord(
  botId: string,
  data: Omit<
    NewMeetingRecordRow,
    "botId" | "status" | "attempts" | "createdAt" | "updatedAt"
  >,
): Promise<void> {
  await scopedDb()
    .update(meetingRecords)
    .set({ ...data, status: "done", error: null, updatedAt: new Date() })
    .where(eq(meetingRecords.botId, botId));
}

/** Marks the minutes as permanently failed (after exhausting retries). */
export async function failMeetingRecord(
  botId: string,
  error: string,
): Promise<void> {
  await scopedDb()
    .update(meetingRecords)
    .set({ status: "failed", error, updatedAt: new Date() })
    .where(eq(meetingRecords.botId, botId));
}

/**
 * Moves the minutes back to "pending" (transient retry: transcript still
 * processing, or recoverable error). The reconciliation cron picks it up on
 * the next tick.
 */
export async function requeueMeetingRecord(
  botId: string,
  note: string,
): Promise<void> {
  await scopedDb()
    .update(meetingRecords)
    .set({ status: "pending", error: note, updatedAt: new Date() })
    .where(eq(meetingRecords.botId, botId));
}

/**
 * Returns botIds of minutes stuck for the reconciliation cron: pending for
 * more than `staleMs`, or failed (for a new attempt). Doesn't touch
 * done/recently processing.
 */
export async function listStuckMeetingRecords(
  staleMs: number,
): Promise<string[]> {
  const threshold = new Date(Date.now() - staleMs);
  const rows = await scopedDb()
    .select({ botId: meetingRecords.botId })
    .from(meetingRecords)
    .where(
      or(
        and(
          eq(meetingRecords.status, "pending"),
          lt(meetingRecords.updatedAt, threshold),
        ),
        and(
          eq(meetingRecords.status, "processing"),
          lt(meetingRecords.updatedAt, threshold),
        ),
      ),
    );
  return rows.map((r) => r.botId);
}
